# Generated by Django 3.0.8 on 2021-05-03 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='love',
        ),
        migrations.AddField(
            model_name='tweet',
            name='love',
            field=models.ManyToManyField(related_name='love', to=settings.AUTH_USER_MODEL),
        ),
    ]
